apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xhr71t35c-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xhr71t35c-dotnet-basic-gitops